# Update the repo, because most boxes are heavily outdated
- name: Common | Update repository
  command: /usr/bin/apt-get update

- name: Common | Apache
  apt: pkg=apache2 state=installed

- name: Common | Apache equired modules
  command: a2enmod $item
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
    - ssl

- name: Common | PHP core and required modules
  apt: pkg=$item state=installed
  notify: restart apache
  with_items:
    - php5
    - php5-mysql
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php-apc
    - php5-curl
    - php5-intl
    - php5-memcache
    - php5-memcached

# Only install the client, you may want to use the DB-server on a different machine
- name: Common | MySQL Client only
  apt: pkg=mysql-client state=installed

# Need this to run mysql commands via Ansible
- name: Common | Ensure python-mysqldb is available
  apt: pkg=python-mysqldb state=installed

# Install ACL, but you'll have to do the mount config yourself in most cases
- name: Common | ACL
  apt: pkg=acl state=installed

- name: Common | cURL
  apt: pkg=curl state=installed

- name: Common | Remove /var/www
  command: rm -rf /var/www

- name: Common | Create a link to /vagrant/www in /var
  command: ln -s {{ www }} /var

# End of file roles/webserver/tasks/main.yml
