---

# Installs specific vhosts if defined
- name: Vhosts | Virtual Host configuration
  template: src=vhost.j2 dest=/etc/apache2/sites-available/{{ item.name }}-{{ item.version }}.local
  with_items: $vhosts

# Make sure the vhost is enabled
- name: Vhosts | Enable virtual hosts
  command: a2ensite {{ item.name }}-{{ item.version }}.local
  with_items: $vhosts
  notify: restart apache

# Removing to /etc/hosts
- name: Vhosts | Removing /etc/hosts
  command: rm -f /etc/hosts

# Adding to /etc/hosts
- name: Vhosts | Adding /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts

# Permissions for PyroCMS
- name: Permissions | system/cms/cache
  command: chmod 777 {{ www }}dev/{{ item.version }}/system/cms/cache
  with_items: $vhosts

- name: Permissions | system/cms/config
  command: chmod 777 {{ www }}dev/{{ item.version }}/system/cms/config
  with_items: $vhosts

- name: Permissions | addons
  command: chmod 777 {{ www }}dev/{{ item.version }}/addons
  with_items: $vhosts

- name: Permissions | assets/cache
  command: chmod 777 {{ www }}dev/{{ item.version }}/assets/cache
  with_items: $vhosts

- name: Permissions | uploads
  command: chmod 777 {{ www }}dev/{{ item.version }}/uploads
  with_items: $vhosts

- name: Permissions | system/cms/config/config.php
  command: chmod 666 {{ www }}dev/{{ item.version }}/system/cms/config/config.php
  with_items: $vhosts

# End of file roles/vhosts/tasks/main.yml
