---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [all] section in the hosts file to determine which machines
# to operate on.
- hosts: all

  sudo: true

  # Looks for roles/{role}/tasks/main.yml for tasks, roles/{role}/handlers/main.yml
  # for handlers, etcetera.
  roles:
    # Standard LAMP stuff, including common Apache and PHP mods, minus MySQL server
    - webserver
    # MySQL server commes separate, you don't want this if you're using an external DB.
    - dbserver
    # Development tools.
    - development
    # Virtual hosts.
    - vhosts

# End of file site.yml
