- name: Development | Install Git
  apt: pkg=$item state=installed
  with_items:
    - git
    - git-gui
    - gitk

- name: Development | Run the Shell Script
  script: bootstrap.sh

# End of file roles/development/tasks/main.yml
